name: Feature request
description: Suggest an idea for this project.
title: "[Request]: "
labels: request
body:
- type: textarea
  attributes:
    label: Problem
    description: Is your feature request related to a problem? Please describe.
    placeholder: A clear description of what the problem is (if any).
  validations:
    required: false

- type: textarea
  attributes:
    label: Description
    description: Describe the solution or feature you're requesting
    placeholder: A clear and consice description of your request.
  validations:
    required: true

- type: textarea
  attributes:
    label: Reason
    description: Provide Reasoning
    placeholder: Tell us why you want this added to YimLaunchpad.
  validations:
    required: true

- type: textarea
  attributes:
    label: Additional context
    description: |
      Add any other context about the request here.
      
      Tip:You can attach images or log files by dragging and dropping them here.
  validations:
    required: false
